### ISSUE TITLE
How long is this repo up to date?

### ISSUE THREAD

**Issue by Sonerry** [stormalf/chibicc#81]
I'm writing this project from scratch. Writing is better for me. I would like to help you after writing (I realized I was wrong in the previous issue, ignore it)

**Comment by stormalf** [comment]
Hi @sonerry,
Well, It's a hobby. I'm using this project, because I'm fascinating by compilers. Chibicc is very well-written, easy to understand and great to work on it, to extend it. I'm for now blocked on issue with vector size found during postgres compilation. Any help is always appreciated. Don't hesitate, if you see bugs and have some ideas about how to fix them.  regards
